version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "daily"
    open-pull-requests-limit: 2          # <- default is 5
    groups:                              # <- group all github actions updates in a single PR
      # 1. development-dependencies are auto-merged
      development-dependencies:
        patterns:
          - '*'

  - package-ecosystem: "gomod"
    # Auto-merging policy, when requirements are met:
    # 1. development-dependencies are auto-merged
    #
    # All dependencies are considered auto-mergeable here.
    #
    # CI performs a vulnerability scan on pull requests:
    # detected vulnerabilities would block a dependabot update to be merged.
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 4
    groups:
      development-dependencies:
        patterns:
          - "*"

